test

diff --git a/.github/workflows/shells-ci.yml b/.github/workflows/shells-ci.yml
--- a/.github/workflows/shells-ci.yml
+++ b/.github/workflows/shells-ci.yml
@@ -84,7 +84,13 @@ jobs:
         run: |
           NODE_TYPE="${{ steps.getNodeType.outputs.result }}"
           SHELL_NAME=`echo ${NODE_TYPE:16} | tr "[:upper:]" "[:lower:]"`
-          [[ $SHELL_NAME == *" shell "* ]] && (echo "You should remove 'Shell' from the Shell name" && exit 1) || echo "not found"
+          if [[ $SHELL_NAME == *" shell "* ]]
+          then
+            echo "You should remove 'Shell' from the Shell name"
+            exit 1
+          else
+            echo "not found"
+          fi
   create-gh-release:
     needs: [pre-commit, pack]
     if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
